### ISSUE TITLE
Router behaviour for case of accesing to "/" trailing URL.

### ISSUE THREAD

**Issue by ra-gg** [ra-gg/rektia#28]
Ex.
- `/` --> route to `_root_#index`
- `/api` --> route to `_root_#api`, not exists that route to `api#index`
- `/api/` --> route to `api#index`
- `/api/` --> when no exists `api#index`, route to `_root_#api`
- `/api/` --> when no exists `api#index` and `_root_#api` to 404

more ex.
- `/api/user` --> route to `api#user`, when it's no exists route to `api/user#index`
- `/api/user/` --> route to `api/user#index`.

On inner behaviour of Router.
Normalized URL is to be ending in "/" or terminated without "/" ?

**Comment by Ragg-** [comment]
now decide.
Router behaviour is `/` sensitive. (follow static file server behavior.)

- `/` --> route to `_root_#index`
- `/api` --> route to `_root_#api`
- `/api/` --> route to `api#index`
- `/api/user` --> route to `api#user`
- `/api/user/` --> route to `api/user#index`
- `/api/user/create` --> route to `api/user#create`

**Comment by Ragg-** [comment]
Currently, can't route to `/index` as `/`.
